[package]
name = "jsl-codegen"
version = "0.1.0"
authors = ["Ulysse Carion <ulyssecarion@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
jsl = { path = "../json-schema-language-rust" }
failure = "0.1"
serde_json = "1.0"
url = "1.7"
Inflector = "0.11"
